spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.95.169.127:3306/pomodoro_study_forum?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 279110233
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  mail:
    host: smtp.qq.com
    username: 1309021068@qq.com
    password: cwzidmpyrclhjbcc
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    nickname: 考研学习管理系统邮件
    properties:
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.timeout": 5000
      "mail.smtp.socketFactory.class": "javax.net.ssl.SSLSocketFactory"  # SSL连接
      "mail.smtp.socketFactory.port": 465   # SSL端口
  data:
    redis:
      host: 1.95.169.127
      port: 6379
      password: fengyang1314
      database: 0
      lettuce:
        pool:
          max-active: 8  #????
          max-idle: 8   #??????
          min-idle: 0   #??????
          max-wait: 100ms #??????


# sa-token??
sa-token:
  token-name: sa-token-authorization
  timeout: 3600
  active-timeout: 1800
  is-concurrent: false
  is-share: true
  token-style: simple-uuid
  is-log: true
  auto-renew: true

mybatis-plus:
  type-aliases-package: com.graduation.his.domain.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#    global-config:
#      db-config:
#        id-type: auto # ??id??????

logging:
  level:
    org.ehcache: debug

